### ISSUE TITLE
build_data.py for converting sejong dataset to training and validation

### ISSUE THREAD

**Issue by februa22** [nlp-research/biaffineparser#10]
CONLL-U to Pandas DataFrame: [https://github.com/interrogator/conll-df](https://github.com/interrogator/conll-df)

**Comment by bart2001** [comment]
별도의 build_data.py(예시) 파일로 구성하여 train.sh에서 사전에 실행하고 학습하도록 구성

**Comment by bart2001** [comment]
@februa22 
build.py 모듈 및 이를 실행하는 쉘스크립트 build.sh 개발 완료

build.sh 스크립트를 옵션을 수정해서 실행하여 사용할 수 있습니다.

* 데이터 포멧에서 추후가 문제가 될 경우 다시 이 이슈를 오픈하거나 새로운 이슈를 만들겠습니다.
